//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.23 at 01:05:46 PM BDT 
//


package io.naztech.abbyy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_festool_extraction_v3">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}_InvoiceTable" maxOccurs="unbounded"/>
 *                   &lt;element name="_lCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="_lRes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                   &lt;element name="_sFestool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="_AssociationMembershipNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="_Order" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "festoolExtractionV3"
})
@XmlRootElement(name = "Documents")
public class Documents {

    @XmlElement(name = "_festool_extraction_v3", required = true)
    protected Documents.FestoolExtractionV3 festoolExtractionV3;

    /**
     * Gets the value of the festoolExtractionV3 property.
     * 
     * @return
     *     possible object is
     *     {@link Documents.FestoolExtractionV3 }
     *     
     */
    public Documents.FestoolExtractionV3 getFestoolExtractionV3() {
        return festoolExtractionV3;
    }

    /**
     * Sets the value of the festoolExtractionV3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documents.FestoolExtractionV3 }
     *     
     */
    public void setFestoolExtractionV3(Documents.FestoolExtractionV3 value) {
        this.festoolExtractionV3 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}_InvoiceTable" maxOccurs="unbounded"/>
     *         &lt;element name="_lCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="_lRes" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="_sFestool" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="_AssociationMembershipNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="_Order" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "invoiceTable",
        "lCurrency",
        "lRes",
        "sFestool",
        "associationMembershipNo",
        "order"
    })
    public static class FestoolExtractionV3 {

        @XmlElement(name = "_InvoiceTable", required = true)
        protected List<InvoiceTable> invoiceTable;
        @XmlElement(name = "_lCurrency", required = true)
        protected String lCurrency;
        @XmlElement(name = "_lRes")
        @XmlSchemaType(name = "unsignedShort")
        protected int lRes;
        @XmlElement(name = "_sFestool", required = true)
        protected String sFestool;
        @XmlElement(name = "_AssociationMembershipNo", required = true)
        protected String associationMembershipNo;
        @XmlElement(name = "_Order", required = true)
        protected Object order;

        /**
         * Gets the value of the invoiceTable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the invoiceTable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInvoiceTable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InvoiceTable }
         * 
         * 
         */
        public List<InvoiceTable> getInvoiceTable() {
            if (invoiceTable == null) {
                invoiceTable = new ArrayList<InvoiceTable>();
            }
            return this.invoiceTable;
        }

        /**
         * Gets the value of the lCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLCurrency() {
            return lCurrency;
        }

        /**
         * Sets the value of the lCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLCurrency(String value) {
            this.lCurrency = value;
        }

        /**
         * Gets the value of the lRes property.
         * 
         */
        public int getLRes() {
            return lRes;
        }

        /**
         * Sets the value of the lRes property.
         * 
         */
        public void setLRes(int value) {
            this.lRes = value;
        }

        /**
         * Gets the value of the sFestool property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSFestool() {
            return sFestool;
        }

        /**
         * Sets the value of the sFestool property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSFestool(String value) {
            this.sFestool = value;
        }

        /**
         * Gets the value of the associationMembershipNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssociationMembershipNo() {
            return associationMembershipNo;
        }

        /**
         * Sets the value of the associationMembershipNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssociationMembershipNo(String value) {
            this.associationMembershipNo = value;
        }

        /**
         * Gets the value of the order property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getOrder() {
            return order;
        }

        /**
         * Sets the value of the order property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setOrder(Object value) {
            this.order = value;
        }

    }

}
