Ext.define('Desktop.constants.ActionType', {
	alias: 'appActionType',
	alternateClassName: 'appActionType',
	statics: {
		ACTION_TYPE_NEW: "NEW",
		ACTION_TYPE_UPDATE: "UPDATE",
		ACTION_TYPE_DELETE: "DELETE",
		ACTION_TYPE_CANCEL: "CANCEL",
		ACTION_TYPE_SELECT: "SELECT",
		ACTION_TYPE_SELECT_LOGIN: "SELECT_LOGIN",
		ACTION_TYPE_LOGIN: "LOGIN",
		ACTION_TYPE_LOGOUT: "LOGOUT",
		ACTION_TYPE_UPDATE_HIT: "UPDATE",
		ACTION_TYPE_AUTHORIZE: 'AUTHORIZE',
		ACTION_TYPE_SEARCH: 'SEARCH',
		ACTION_TYPE_SELECT_DOC_DETAILS: 'SELECT_DOC_DETAILS',
		ACTION_TYPE_UPDATE_DOC_DETAILS: 'UPDATE_DOC_DETAILS',
		ACTION_TYPE_NEW_DOC_DETAILS: 'NEW_DOC_DETAILS',
		ACTION_TYPE_SELECT_CUSTOMER: 'SELECT_CUSTOMER',
		ACTION_TYPE_UPDATE_CUSTOMER: 'UPDATE_CUSTOMER'
		
	}
});